#rename this file to "cloudbuild.yaml" and put it in your github repo
#refactor variables as needed

#be-a-man-10 in this example is the service name
#berronspage is the app name
#ultramarines-armageddon is the name we are giving to the artifact repo

# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - 'run'
#     - 'deploy'
#     - 'be-aman-10' #app-name
#     - '--image=southamerica-east1.pkg.dev/$PROJECT_ID/ultramarines-armageddon/be-a-man-10:$COMMIT_SHA'
#     - '--source=.'
#     - '--region=southamerica-east1'
#     - '--project=$PROJECT_ID'
# images:
# - 'southamerica-east1.pkg.dev/$PROJECT_ID/ultramarines-armageddon/be-a-man-10:$COMMIT_SHA'
